apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-service
  template:
    metadata:
      labels:
        app: contact-service
    spec:
      containers:
        - name: contact-service
          image: brahim20255/contact-service:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url" : "jdbc:mysql://mysql-pfe-service:3306//pfe_db"}'
          ports:
            - containerPort:  8089
---
apiVersion: v1
kind: Service
metadata:
  name: contact-service
spec:
  ports:
    - port:  8089
      targetPort:  8089
  selector:
    app: contact-service
