apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formation-service
  template:
    metadata:
      labels:
        app: formation-service
    spec:
      containers:
        - name: formation-service
          image: brahim20255/formation-service:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url" : "jdbc:mysql://mysql-pfe-service:3306//pfe_db"}'
          ports:
            - containerPort:  8088
---
apiVersion: v1
kind: Service
metadata:
  name: formation-service
spec:
  ports:
    - port:  8088
      targetPort:  8088
  selector:
    app: formation-service
