apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: brahim20255/login-service:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url" : "jdbc:mysql://mysql-pfe-service:3306//pfe_db"}'
          ports:
            - containerPort:  8084
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  ports:
    - port:  8084
      targetPort:  8084
  selector:
    app: login-service
