apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-product-service
  template:
    metadata:
      labels:
        app: mongo-product-service
    spec:
      containers:
        - name: mongo-product-service
          image: mongo:4.4.14-rc0-focal
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-product-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-product-service
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
