apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: brahim20255/notification-service:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url" : "jdbc:postgresql://postgres-notification-service:5432/notification_service"}'
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: notification-service
