apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: brahim20255/order-service:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.datasource.url" : "jdbc:mysql://mysql-pfe-service:3306//pfe_db"}'
          ports:
            - containerPort:  8086
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port:  8086
      targetPort:  8086
  selector:
    app: order-service
